title : Karhu story
tagline: an adventure that pulls you in
author : Karlos Zafra
email : karlos.zafra@gmail.com
content: Karhu by Koi Studio
github : solkar
twitter : solkar
fb: therealsolkar
mailingListForm: http://tumblr.us7.list-manage.com/subscribe/post?u=94c0a37c08760aed271d06edf&amp;id=169238ccaf
